services:
  api:
    image: loggingandmetricsapi
    build:
      context: .
      dockerfile: LoggingAndMetricsAPI/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - my-network
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - my-network

networks:
  my-network:
    driver: bridge